#!/bin/bash
echo -e ""
echo -e "» AutoScript v1.0"
echo -e "» menu          : Menu de Opciones"
echo -e "» nuevo         : Crear cuenta SSH & OpenVPN"
echo -e "» prueba        : Crear cuenta de prueba"
echo -e "» borrar        : Borrar cuenta SSH & OpenVPN"
echo -e "» checar        : Verificar o modificar usuario"
echo -e "» lista         : Listado de usuarios SSH & OpenVPN"
echo -e "» expirado      : Borrar usuario expirado"
echo -e "» restart       : Restart servicios dropbear, webmin"
echo -e "                 squid3, OpenVPN,Stunnel y SSH"
echo -e "» reboot        : Reboot VPS"
echo -e "» speedtest     : Speedtest VPS"
echo -e "» info          : Informacion del Sistema"
echo -e "» acerca        : Acerca del Script"
echo -e "» exit          : Salir de la cuenta SSH"
echo -e ""
